# CORRECTED netlify.toml

[build]
  # Tell Netlify to change to the frontend folder AND run the build command
  command = "cd frontend && npm install && npm run build"
  
  # The publish directory is now relative to the root
  publish = "frontend/build"
  
  # The functions directory is also relative to the root
  functions = "api/"

# This rewrite rule remains the same and is correct
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200