# FINAL, SIMPLIFIED netlify.toml

[build]
  # 1. Install Python dependencies from the root
  # 2. THEN change to the frontend folder, install JS dependencies, and build
  command = "pip install -r requirements.txt && cd frontend && npm install && npm run build"
  
  publish = "frontend/build"
  functions = "api/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200